define({ root:
//begin v1.x content
({
	prefixAgo: null,
    prefixFromNow: null,
    suffixAgo: "ago",
    suffixFromNow: "from now",
    now: " just a moment",
    seconds: "less than a minute",
    minute: "about a minute",
    minutes: "%d minutes",
    hour: "about an hour",
    hours: "about $d hours",
    day: "a day",
    days: "%d days",
    month: "about a month",
    months: "%d months",
    year: "about a year",
    years: "%d years",
    numbers: []
})
//end v1.x content
,
"zh": false,
"zh-tw": false,
"tr": false,
"th": false,
"sv": false,
"sl": false,
"sk": false,
"ru": false,
"ro": false,
"pt": false,
"pt-pt": false,
"pl": false,
"nl": false,
"nb": false,
"ko": false,
"kk": false,
"ja": false,
"it": false,
"hu": false,
"he": false,
"fr": false,
"fi": false,
"es": false,
"el": false,
"de": false,
"da": false,
"cs": false,
"ca": false,
"ar": false
});
